# Generated by Django 2.2 on 2020-12-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescategory',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Описание '),
        ),
        migrations.AlterField(
            model_name='gamescategory',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название игры')),
                ('desc', models.TextField(blank=True, verbose_name='Описание игры')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.GamesCategory')),
            ],
        ),
    ]
