# Generated by Django 2.2 on 2020-12-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201217_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='date',
        ),
    ]
