# Generated by Django 2.2 on 2020-12-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_games_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Игры', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gamescategory',
            options={'verbose_name': 'Категории игр', 'verbose_name_plural': 'Категория игр'},
        ),
    ]
